<script lang="ts">
	export let location;
	export let navigate;
</script>

<svelte:head>
	<title>Treinamentos - Learning Platform</title>
</svelte:head>
<div>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
	<h1>Treinamento</h1>
</div>
